### ISSUE TITLE
Allow running on vanilla lnd (no fork)

### ISSUE THREAD

**Issue by joostjager** [joostjager/whatsat#1]
The changes required to `lnd` to be able to run Whatsat as a standalone process are relatively modest and involve no modifications to the wire protocol.

In order to send a chat message, we need to be able to attach the message and the signature to a payment request: https://github.com/lightningnetwork/lnd/issues/3670

To intercept failed payment requests and extract the message and signature, a version of https://github.com/lightningnetwork/lnd/pull/3639 is required. It is important that the rpc interface exposes the tlv data of the failed payment. It also needs to do this in a way that allows us to catch up with missed messages. Furthermore, received messages should survive restarts of `lnd`.

When starting to pay for chat messages, it is no longer necessary to intercept failures: https://github.com/joostjager/whatsat/issues/2

**Comment by Sjors** [comment]
Does this also mean the Whatsat repo can be made a standalone tool that uses Lnd via RPC, rather than a fork of Lnd?

**Comment by joostjager** [comment]
Yes, that is the idea. This also allows existing wallet apps that connect to a node remotely to add a 'chat tab'.

**Comment by joostjager** [comment]
All requirements are merged into lnd master now

**Comment by leto** [comment]
@joostjager this is great news. Would you mind documenting things again with how they currently work, with an eye towards non-LN-devs such as myself? I am interesting to try thing out
