### ISSUE TITLE
Pay for chat messages

### ISSUE THREAD

**Issue by joostjager** [joostjager/whatsat#2]
In the current Lightning Network, it is possible to chat for free. This may change in the future. If that is the case, the receiver of a message needs to settle the htlc and the sender will pay for it.

This requires several changes:
* It is no longer necessary for receivers to intercept failed payment requests. The custom payload chat message can be retrieved from the invoice database.
* Currently the htlc amount for a chat message is fixed at 100 sat. The amount does not matter much, because the htlc is canceled anyway. If the htlc is going to be settled, this will change. Senders only want to pay to routing nodes. It seems unlikely that they'll also want to pay the receiver of the message. Ideally, the receiver gets an htlc for amount 0. If that creates implementation difficulties, it could also be the negligible amount of 1 millisatoshi. 
* Because actual payments happen, a sender needs to carefully set the maximum routing fee per message.
* If routing proves to be difficult because of minimum htlc amount constraints on channels, a fall back option is to pay a larger amount to the recipient to satisfy those constraints and ensure that the recipient sends the amount back in the reply. Making sure that the balance between sender and recipient hovers around 0.
* The payload also need to contain the payment hash preimage, because chat messages will be spontaneous payments.

**Comment by joostjager** [comment]
Implemented part of this in `master`

**Comment by joostjager** [comment]
Paying for messages is now the only supported mode for chatting.

**Comment by zciendor** [comment]
>  It seems unlikely that they'll also want to pay the receiver of the message.

But it's quite likely the receiver wants to get paid a certain amount to read the message as a kind of anti-spam feature. Like for example: "I'm very busy, my time is precious and I'll only look at messages the sender is willing to pay 1000 sats. It's up to the senders to decide if they think their message content is them worth that amount."

This is definitely a per-user decision what they want to set as a minimum threshold.
